# Generated by Django 3.2.3 on 2021-06-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210602_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/images/default_pic.png', upload_to='images/'),
        ),
    ]
